language: node_js
node_js:
  - "12"

after_success:
  - npm run lint
  - npm run build
before_deploy:
  - cd dist

deploy:
  provider: npm
  email: $NPM_EMAIL
  skip_cleanup: true
  api_key:
    secure: $NPM_TOKEN
  on:
    branch: master
    tags: true
